apiVersion: v1
kind: Namespace
metadata:
  name: resume-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: resume-app
data:
  ENVIRONMENT: production
  LOG_LEVEL: info
  VITE_API_URL: http://backend-service.resume-app.svc.cluster.local:5000
